name: Pull-Request Check (Lint, Typecheck, Test, Build)

on:
  pull_request:
    branches: [ main ]

jobs:
  pr-check:
    name: Lint, Typecheck, Test, Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r requirements-dev.txt
          pip install build twine

      - name: Lint and type check
        run: |
          black --check .
          ruff check .
          pyright

      - name: Run tests
        run: pytest

      - name: Build package
        run: python -m build

      - name: Check with Twine
        run: twine check dist/*

